version: '2'
services:
  wordpress:
    image: wordpress
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    image: mysql
    cpu_shares: 100
    mem_limit: 524288000
    environment:
      MYSQL_ROOT_PASSWORD: password
  inception:
    image: 766806801073.dkr.ecr.us-east-1.amazonaws.com/inception:latest
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "9000:9000"
    command: ["/bin/sh", "-c", "/serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=inception --model_base_path=/serving/inception-export"]
